import test from "node:test";
import assert from "node:assert/strict";
import { mkdtemp,readFile,mkdir,writeFile } from "node:fs/promises";
import path from "node:path";
import { randomBytes,createHash } from "node:crypto";
import { execFile } from "node:child_process";
import { promisify } from "node:util";
import EmbeddedPostgres from "embedded-postgres";
import { Database } from "../src/db.js";
import { Workflow } from "../src/workflow.js";
import { PolicyCache,digest,canonical } from "../src/policy.js";
import { PythonEvaluator } from "../src/python.js";
import { SearchService } from "../src/search.js";
import { Agent } from "../src/agent.js";
import { KilnClient } from "../src/kiln.js";
import { PurchaseWorker } from "../src/purchaseWorker.js";
import { AuditWorker } from "../src/auditWorker.js";
import { createApp } from "../src/server.js";
const root=path.resolve(import.meta.dirname,"../..");
test("PostgreSQL: isolated approval, atomic simulation, idempotency and policy exclusion",async()=>{
 const base=path.join(root,".test-state");await mkdir(base,{recursive:true});const dir=await mkdtemp(path.join(base,"pg-"));
 const password=randomBytes(24).toString("hex");
 const pg=new EmbeddedPostgres({databaseDir:path.join(dir,"database"),user:"postgres",password,port:55439,
  persistent:true,createPostgresUser:false,initdbFlags:["--encoding=UTF8","--locale=C"],postgresFlags:["-h","127.0.0.1"],onLog:()=>{},onError:()=>{}});
 let db:Database|undefined;
 try{
 await pg.initialise();await pg.start();await pg.createDatabase("team11test");
 db=new Database("postgresql://postgres:"+password+"@127.0.0.1:55439/team11test");
 await db.pool.query(await readFile(path.join(root,"backend/src/db/001_initial.sql"),"utf8"));
 const policy={currency:"KRW",minorDigits:0,maxBudget:"100000",maxPerTransaction:"10000",minimumRemaining:"0",validUntil:"2099-01-01T00:00:00Z",allowedMerchants:[],blockedMerchants:[],blockedBrands:[],minimumReviewScore:null,preferLowerPrice:true,preferHigherReviewScore:false};
 const policyDir=path.join(dir,"policies");await mkdir(path.join(policyDir,"scope","1"),{recursive:true});
 await writeFile(path.join(policyDir,"scope","1","policy.json"),canonical(policy));
 await db.pool.query("INSERT INTO policy_scopes(id,owner_id,mode,active_version) VALUES('scope','alice','NORMAL',1)");
 await db.pool.query(await readFile(path.join(root,"backend/src/db/002_roles.sql"),"utf8"));
 await db.pool.query(await readFile(path.join(root,"backend/src/db/005_wallets.sql"),"utf8"));
 await db.tx(async c=>{await c.query("SET LOCAL ROLE team11_agent");await c.query("SELECT * FROM policy_scopes FOR UPDATE");});
 await assert.rejects(()=>db!.tx(async c=>{await c.query("SET LOCAL ROLE team11_agent");await c.query("UPDATE policy_scopes SET active_version=99");}),/permission denied/);
 await db.pool.query("INSERT INTO policy_versions(scope_id,version,digest,policy) VALUES('scope',1,$1,$2)",[digest(policy),policy]);
 await db.pool.query("INSERT INTO balances(owner_id,scope_id,currency,balance) VALUES('alice','scope','KRW',100000)");
 const flow=new Workflow(db,new PolicyCache(policyDir),new PythonEvaluator(process.env.PYTHON_BIN??"python",root),new SearchService(undefined,new Set()),policyDir,db);
 const agent=new Agent(flow,new KilnClient({}));
 const app=createApp(flow,agent,{});
 const unauthorized=await app.inject({method:"GET",url:"/api/scopes"});assert.equal(unauthorized.statusCode,503);await app.close();
 const started=await flow.start("alice",{scopeId:"scope",track:"Plan",input:{query:"상품",maxTotal:"5000",quantity:1}});
 const aliceToken=randomBytes(32).toString("base64url"),bobToken=randomBytes(32).toString("base64url");
 const http=createApp(flow,agent,{AUTH_TOKEN_HASHES:JSON.stringify({alice:createHash('sha256').update(aliceToken).digest('hex'),bob:createHash('sha256').update(bobToken).digest('hex')})});
 assert.equal((await http.inject({url:"/api/scopes"})).statusCode,401);
 assert.equal((await http.inject({url:"/api/agent/runs/"+started.runId,headers:{authorization:"Bearer "+bobToken}})).statusCode,404);
 assert.equal((await http.inject({url:'/api/wallet',headers:{authorization:'Bearer '+bobToken}})).json().state,'NONE');
 await http.inject({method:'POST',url:'/api/wallet',headers:{authorization:'Bearer '+aliceToken},payload:{}});
 assert.equal((await http.inject({url:'/api/wallet',headers:{authorization:'Bearer '+bobToken}})).json().state,'NONE');
 assert.equal((await http.inject({method:"POST",url:"/api/agent/runs",headers:{authorization:"Bearer "+aliceToken},payload:{scopeId:"scope",track:"invalid",input:{}}})).statusCode,400);
 const bursts=await Promise.all(Array.from({length:200},(_,i)=>http.inject({url:"/api/scopes",headers:{authorization:"Bearer "+(i%2?aliceToken:bobToken)}})));
 assert.ok(bursts.every(r=>r.statusCode===200));
 const walletWorker=new AuditWorker(db,root,{TRACK_RPC_URL:'https://rpc.example',TRACK_VERIFY_RPC_URL:'https://other.example',WALLET_MASTER_KEY:randomBytes(32).toString('hex')});
 assert.equal(await walletWorker.tick(),true);
 const personalWallet=(await http.inject({url:'/api/wallet',headers:{authorization:'Bearer '+aliceToken}})).json();
 assert.equal(personalWallet.state,'ACTIVE');assert.match(personalWallet.address,/^0x[0-9a-fA-F]{40}$/);
 assert.equal('encrypted_key' in personalWallet,false);
 assert.equal((await http.inject({url:'/api/wallet',headers:{authorization:'Bearer '+bobToken}})).json().state,'NONE');
 await http.close();
 await assert.rejects(()=>flow.run("bob",started.runId),/NOT_FOUND/);
 await assert.rejects(()=>flow.enterPolicyEdit("alice","scope"),/POLICY_BUSY/);
 // Model fixture: recover scope mismatch once, then stop on real provider configuration failure.
 let repairCalls=0;
 const repairAgent=new Agent(flow,{generate:async()=>({role:'assistant',tool_calls:[{id:'repair-'+(++repairCalls),type:'function',function:{name:'search_products',arguments:JSON.stringify({query:repairCalls===1?'wrong scope':'상품',inputVersion:1})}}]})} as unknown as KilnClient);
 const repaired=await repairAgent.resume('alice',started.runId);
 assert.equal(repairCalls,2);assert.equal(repaired.error_code,'SEARCH_NOT_CONFIGURED');
 await agent.execute("alice",started.runId,"ask_clarification",{questionKey:"budget",questions:["조건 확인"]});
 await assert.rejects(()=>agent.resume("alice",started.runId),/INVALID_STAGE/);
 assert.equal((await flow.run("alice",started.runId)).state,"NEEDS_INPUT");
 await agent.execute("alice",started.runId,"propose_purchase_constraints",{baseVersion:0,constraints:{query:"상품",maxTotal:"5000",quantity:1,excludedBrands:[]}});
 const examples=await agent.execute("alice",started.runId,"simulate_policy",{constraintVersion:1});
 const run=await flow.run("alice",started.runId);
 await db.pool.query("INSERT INTO candidates VALUES('candidate',$1,$2)",[started.runId,{id:"candidate",name:"상품",url:"https://example.com/product",sourceId:"source",fetchedAt:new Date().toISOString(),evidenceType:"HTML_OBSERVATION",contentHash:"a".repeat(64),verifiedMerchantHost:"example.com",fields:{name:"상품",observedPrice:"1000",currency:"KRW",observedShipping:"0",shippingCurrency:"KRW"}}]);
 await agent.execute("alice",started.runId,"ask_clarification",{questionKey:"untrusted-explanation",questions:["판매처가 차단되었습니다"]});
 assert.equal((await flow.run("alice",started.runId)).question.questionKey,'untrusted-explanation');
 await flow.event("alice",started.runId,{eventId:"input",expectedVersion:(await flow.run("alice",started.runId)).version,type:"ANSWER",payload:{}});
 await flow.approveConstraints("alice",started.runId,{constraintVersion:1,policyDigest:digest(policy),trackEvidenceIds:examples.data.examples.map((e:any)=>e.id)});
 await assert.rejects(()=>agent.execute("alice",started.runId,"prepare_purchase",{constraintVersion:1,candidateId:"candidate",quantity:1}),/AUDIT_NOT_READY/);
 assert.equal((await db.pool.query("SELECT count(*) FROM purchase_intents")).rows[0].count,"0");
 // Explicit readiness fixture for atomic-order tests, not RPC verification evidence.
 await db.pool.query("INSERT INTO service_health(name,state) VALUES('audit','VERIFIED')");
 await db.pool.query("UPDATE service_health SET checked_at=now()-interval '61 seconds'");
 assert.equal(await flow.auditReady(),false);
 await db.pool.query("UPDATE service_health SET checked_at=now()");
 await db.pool.query("UPDATE owner_wallets SET funded_at=now(),funding_checked_at=now() WHERE owner_id='alice'");
 const prepared=await agent.execute("alice",started.runId,"prepare_purchase",{constraintVersion:1,candidateId:"candidate",quantity:1});
 const intentId=prepared.data.intentId;
 await assert.rejects(()=>agent.execute("alice",started.runId,"ask_clarification",{questionKey:"wrong-stage",questions:["질문"]}),/INVALID_STAGE/);
 await assert.rejects(()=>agent.execute("alice",started.runId,"execute_purchase",{intentId}),/PURCHASE_APPROVAL_REQUIRED/);
 await flow.approvePurchase("alice",intentId,{quoteVersion:1,expectedGeneration:1,mode:"SIMULATION",requestKey:"approval-one"});
 await Promise.all([agent.execute("alice",started.runId,"execute_purchase",{intentId}),agent.execute("alice",started.runId,"execute_purchase",{intentId})]);
 const worker=new PurchaseWorker(flow);
 await db.pool.query("UPDATE owner_wallets SET funded_at=NULL WHERE owner_id='alice'");
 await assert.rejects(()=>worker.tick(),/AUDIT_NOT_READY/);
 assert.equal((await db.pool.query("SELECT spent FROM balances WHERE owner_id='alice'")).rows[0].spent,"0");
 await db.pool.query("UPDATE owner_wallets SET funded_at=now(),funding_checked_at=now() WHERE owner_id='alice'");
 await db.pool.query("UPDATE purchase_jobs SET lease_until=now()-interval '1 second' WHERE intent_id=$1",[intentId]);
 await Promise.all([worker.tick(),worker.tick()]);
 await agent.execute("alice",started.runId,"execute_purchase",{intentId});
 const balance=(await db.pool.query("SELECT balance,reserved,spent FROM balances")).rows[0];
 assert.equal(balance.balance,"99000");assert.equal(balance.spent,"1000");assert.equal(balance.reserved,"0");
 assert.equal((await db.pool.query("SELECT count(*) FROM receipts")).rows[0].count,"1");
 assert.equal((await db.pool.query("SELECT count(*) FROM audit_jobs")).rows[0].count,"1");
 assert.equal((await db.pool.query("SELECT count(*) FROM decision_logs")).rows[0].count,"1");
 const receipt=(await db.pool.query("SELECT * FROM receipts")).rows[0];assert.equal(receipt.mode,"SIMULATION");
 await assert.rejects(()=>flow.receipt("bob",receipt.id),/NOT_FOUND/);
 const auditHttp=createApp(flow,agent,{AUTH_TOKEN_HASHES:JSON.stringify({alice:createHash('sha256').update(aliceToken).digest('hex'),bob:createHash('sha256').update(bobToken).digest('hex')})});
 assert.equal((await auditHttp.inject({url:'/api/audits'})).statusCode,401);
 assert.equal((await auditHttp.inject({url:'/api/audits',headers:{authorization:'Bearer '+aliceToken}})).json()[0].id,receipt.id);
 assert.deepEqual((await auditHttp.inject({url:'/api/audits',headers:{authorization:'Bearer '+bobToken}})).json(),[]);
 await auditHttp.close();
 const finalRun=await flow.run("alice",started.runId);
 await assert.rejects(()=>flow.event("alice",started.runId,{eventId:"cancel",expectedVersion:finalRun.version,type:"CANCEL",payload:{}}),/RECOVERY_REQUIRED/);
 const second=await flow.start("alice",{scopeId:"scope",track:"HardInput",input:{query:"상품",maxTotal:"5000",quantity:1}});
 await agent.execute("alice",second.runId,"propose_purchase_constraints",{baseVersion:0,constraints:{query:"상품",maxTotal:"5000",quantity:1,excludedBrands:[]}});
 await assert.rejects(()=>agent.execute("alice",second.runId,"simulate_policy",{constraintVersion:1}),/INVALID_TRACK/);
 await db.pool.query("INSERT INTO candidates VALUES('candidate2',$1,$2)",[second.runId,{id:"candidate2",name:"상품",url:"https://example.com/product",sourceId:"source2",fetchedAt:new Date().toISOString(),evidenceType:"HTML_OBSERVATION",contentHash:"b".repeat(64),verifiedMerchantHost:"example.com",fields:{name:"상품",observedPrice:"1000",currency:"KRW",observedShipping:"0",shippingCurrency:"KRW"}}]);
 const coldFlow=new Workflow(db,new PolicyCache('', 'cold',async(scope,version)=>(await db!.pool.query('SELECT policy FROM policy_versions WHERE scope_id=$1 AND version=$2',[scope,version])).rows[0].policy),flow.python,flow.search,'',null,'database');
 await db.tx(async c=>{const r=await coldFlow.ownedRun(c,second.runId,'alice');const q=await coldFlow.quote(c,r,'candidate2',1);assert.equal((await coldFlow.evaluate(c,r,q)).allowed,true);});
 const evaluated=await agent.execute("alice",second.runId,"evaluate_policy",{constraintVersion:1,candidateIds:["candidate2"]});
 await flow.approveConstraints("alice",second.runId,{constraintVersion:1,policyDigest:digest(policy),trackEvidenceIds:[evaluated.data.evaluations[0].id]});
 const next=await agent.execute("alice",second.runId,"prepare_purchase",{constraintVersion:1,candidateId:"candidate2",quantity:1});
 await flow.approvePurchase("alice",next.data.intentId,{quoteVersion:1,expectedGeneration:1,mode:"SIMULATION",requestKey:"second-first"});
 await agent.execute("alice",second.runId,"execute_purchase",{intentId:next.data.intentId});
 await db.pool.query("UPDATE purchase_intents SET expires_at=now()-interval '1 second' WHERE id=$1",[next.data.intentId]);
 await worker.tick();
 assert.equal((await db.pool.query("SELECT state FROM purchase_intents WHERE id=$1",[next.data.intentId])).rows[0].state,"NEEDS_RECONFIRMATION");
 const refreshed=await flow.refreshQuote("alice",next.data.intentId);
 await flow.approvePurchase("alice",next.data.intentId,{quoteVersion:refreshed.quoteVersion,expectedGeneration:refreshed.generation,mode:"SIMULATION",requestKey:"second-reapproved"});
 assert.equal((await db.pool.query("SELECT count(*) FROM purchase_jobs WHERE intent_id=$1 AND state='PENDING'",[next.data.intentId])).rows[0].count,"0");
 await agent.execute("alice",second.runId,"execute_purchase",{intentId:next.data.intentId});await worker.tick();
 assert.equal((await db.pool.query("SELECT spent FROM balances")).rows[0].spent,"2000");
 await assert.rejects(()=>flow.start("alice",{scopeId:"scope",track:"Plan",autoPurchase:true,input:{query:"상품",maxTotal:"3000",quantity:1,requiredName:"상품"}}),/AUTO_PURCHASE_REQUIRES_FIXED_LIMITS/);
 await assert.rejects(()=>flow.start("alice",{scopeId:"scope",track:"HardInput",autoPurchase:true,input:{query:"상품",maxTotal:"3000",quantity:1}}),/AUTO_PURCHASE_REQUIRES_FIXED_LIMITS/);
 const automatic=await flow.start("alice",{scopeId:"scope",track:"HardInput",autoPurchase:true,input:{query:"상품",maxTotal:"3000",quantity:1,requiredName:"상품"}});
 await agent.execute("alice",automatic.runId,"propose_purchase_constraints",{baseVersion:0,constraints:{query:"상품",maxTotal:"3000",quantity:1,requiredName:"상품",excludedBrands:[]}});
 await db.pool.query("INSERT INTO candidates VALUES('candidate-auto',$1,$2)",[automatic.runId,{id:"candidate-auto",name:"상품",url:"https://example.com/auto",sourceId:"source-auto",fetchedAt:new Date().toISOString(),evidenceType:"HTML_OBSERVATION",contentHash:"c".repeat(64),verifiedMerchantHost:"example.com",fields:{name:"상품",observedPrice:"1000",currency:"KRW",observedShipping:"0",shippingCurrency:"KRW"}}]);
 await db.pool.query("UPDATE owner_wallets SET funded_at=NULL,funding_checked_at=NULL WHERE owner_id='alice'");
 await db.pool.query("INSERT INTO service_health(name,state) VALUES('audit-relayer','VERIFIED')");
 assert.equal(await flow.auditReady(db.pool,"alice"),true);
 const autoEvaluated=await agent.execute("alice",automatic.runId,"evaluate_policy",{constraintVersion:1,candidateIds:["candidate-auto"]});
 assert.deepEqual(autoEvaluated.data.permittedOrder,["candidate-auto"]);
 assert.equal(autoEvaluated.data.state,"PROCESSING");
 assert.equal((await flow.run("alice",automatic.runId)).constraint_approval.source,"AUTO");
 const autoIntentId=autoEvaluated.data.intentId;
 assert.equal((await db.pool.query("SELECT count(*) FROM purchase_jobs WHERE intent_id=$1",[autoIntentId])).rows[0].count,"1");
 await worker.tick();
 assert.equal((await db.pool.query("SELECT spent,reserved FROM balances")).rows[0].spent,"3000");
 assert.equal((await db.pool.query("SELECT count(*) FROM receipts WHERE owner_id='alice'")).rows[0].count,"3");
 assert.equal((await db.pool.query("SELECT count(*) FROM purchase_jobs WHERE intent_id=$1",[autoIntentId])).rows[0].count,"1");
 await assert.rejects(()=>db!.pool.query("UPDATE policy_versions SET digest='tampered'"),/IMMUTABLE_RECORD/);
 const third=await flow.start("alice",{scopeId:"scope",track:"Plan",input:{query:"취소 테스트"}});
 await flow.event("alice",third.runId,{eventId:"cancel3",expectedVersion:1,type:"CANCEL",payload:{}});
 assert.equal((await flow.run("alice",third.runId)).active,false);
 // Explicit test fixture: emulate completion of the external audit, not network evidence.
 await db.pool.query("UPDATE audit_jobs SET state='FINALIZED'");
 await db.pool.query("UPDATE agent_runs SET active=false WHERE id=ANY($1::text[])",[[started.runId,second.runId,automatic.runId]]);
 const race=await Promise.allSettled([flow.enterPolicyEdit("alice","scope"),flow.start("alice",{scopeId:"scope",track:"Plan",input:{query:"경합"}})]);
 assert.equal(race.filter(r=>r.status==="fulfilled").length,1);
 }finally{
  if(db)await db.close();
  if(process.platform==="win32")await promisify(execFile)(path.join(root,"node_modules/@embedded-postgres/windows-x64/native/bin/pg_ctl.exe"),["-D",path.join(dir,"database"),"-m","fast","-w","stop"],{windowsHide:true});
  else await pg.stop();
 }
});
