export const toolDefinitions=[
 {name:"ask_clarification",description:"Ask unresolved questions; never approve for the user.",properties:{questionKey:{type:"string"},questions:{type:"array",minItems:1,maxItems:10,items:{type:"string",maxLength:500}}},required:["questionKey","questions"]},
 {name:"propose_purchase_constraints",description:"Propose purchase constraints within the immutable policy.",properties:{baseVersion:{type:"integer",minimum:0},constraints:{type:"object",properties:{query:{type:"string",maxLength:600},maxTotal:{type:"string",pattern:"^[0-9]+$"},quantity:{type:"integer",minimum:1},requiredName:{type:"string"},excludedBrands:{type:"array",items:{type:"string"}}},required:["query","maxTotal","quantity","excludedBrands"],additionalProperties:false}},required:["baseVersion","constraints"]},
 {name:"search_products",description:"Search actual sources. query MUST exactly copy input.query or the current constraints.query, including spaces. To shorten a request, propose_purchase_constraints first, then copy that query. inputVersion MUST match the current run.",properties:{query:{type:"string",maxLength:600},inputVersion:{type:"integer",minimum:1},cursor:{type:"string",maxLength:100}},required:["query","inputVersion"]},
 {name:"simulate_policy",description:"Show one or two deterministic educational examples for Track Plan.",properties:{constraintVersion:{type:"integer",minimum:1}},required:["constraintVersion"]},
 {name:"evaluate_policy",description:"Evaluate source-backed candidates with Python and current simulation balance.",properties:{constraintVersion:{type:"integer",minimum:1},candidateIds:{type:"array",minItems:1,maxItems:20,items:{type:"string"}}},required:["constraintVersion","candidateIds"]},
 {name:"prepare_purchase",description:"Prepare a SIMULATION quote. An explicitly opted-in fixed-limit run auto-enqueues one simulated order after deterministic checks; otherwise ask for approval. Single item for audit v1.",properties:{constraintVersion:{type:"integer",minimum:1},candidateId:{type:"string"},quantity:{type:"integer",minimum:1}},required:["constraintVersion","candidateId","quantity"]},
 {name:"execute_purchase",description:"Enqueue only a user-approved SIMULATION order.",properties:{intentId:{type:"string"}},required:["intentId"]},
 {name:"get_receipt",description:"Read an owned simulation receipt.",properties:{receiptId:{type:"string"}},required:["receiptId"]},
 {name:"get_audit_status",description:"Read actual Sepolia audit evidence for an owned simulation receipt.",properties:{receiptId:{type:"string"}},required:["receiptId"]}
].map(t=>({type:"function" as const,function:{name:t.name,description:t.description,parameters:{type:"object",properties:t.properties,required:t.required,additionalProperties:false}}}));
