import '@fontsource/ibm-plex-sans-kr/400.css';
import '@fontsource/ibm-plex-sans-kr/500.css';
import '@fontsource/ibm-plex-sans-kr/600.css';
import '@fontsource/ibm-plex-mono/400.css';
import './style.css';
import './glass.css';
import {explain,stateNames} from './messages';
const app=document.querySelector<HTMLDivElement>('#app')!;
let token='',connected=false,health:any=null,policy:any=null,run:any=null,edit:any=null;
let scopes:any[]=[],history:any[]=[],recent:any[]=[],audit:any=null,receipt:any=null;
let page='purchase',scope='',policyExpanded=false,busy=false,notice='',isError=false,connectionOpen=true,selected='';
const e=(v:any)=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const name=(s:string)=>stateNames[s]??s;
const value=(id:string)=>(document.getElementById(id) as HTMLInputElement)?.value??'';
const check=(id:string)=>(document.getElementById(id) as HTMLInputElement)?.checked??false;
const dis=(v:any)=>v?' disabled':'';
const date=(v:any)=>v?new Date(v).toLocaleString('ko-KR',{timeZone:'Asia/Seoul'}):'—';
function money(v:any,c=policy?.policy.currency??'KRW',d=policy?.policy.minorDigits??0){
 if(v==null)return '확인 필요';try{const n=BigInt(v),b=10n**BigInt(d);return (n/b).toLocaleString('ko-KR')+(d?'.'+String(n%b).padStart(d,'0'):'')+' '+c;}catch{return '확인 필요';}
}
const badge=(s:string,k='neutral')=>`<span class="badge ${k}">${e(s)}</span>`;
const field=(id:string,title:string,v:any='',type='text',extra='')=>`<label class="field" for="${id}"><span>${title}</span><input id="${id}" type="${type}" value="${e(v)}" ${extra}></label>`;
const amount=(id:string,title:string,v:any='',required=false)=>field(id,title,v,'text',`inputmode="numeric" pattern="[0-9]+" maxlength="15" ${required?'required':''}`);
const row=(title:string,v:any)=>`<div><dt>${title}</dt><dd>${v}</dd></div>`;
const errorBox=(code:string)=>`<div class="callout warning"><strong>확인이 필요합니다</strong><p>${e(explain(code))}</p><small>오류 코드 · ${e(code)}</small></div>`;
async function api(url:string,method='GET',body?:unknown){
 let res:Response;try{res=await fetch('/api'+url,{method,headers:{'Content-Type':'application/json',...(token?{Authorization:'Bearer '+token}:{})},...(body===undefined?{}:{body:JSON.stringify(body)})});}catch{throw Error('SERVICE_UNAVAILABLE');}
 let data:any;try{data=res.headers.get('content-type')?.includes('application/json')?await res.json():null;}catch{data=null;}
 if(!res.ok||!data)throw Error(data?.error??(url.startsWith('/policy-edit')?'POLICY_ADMIN_UNAVAILABLE':'SERVICE_UNAVAILABLE'));return data;
}
async function refresh(){if(run)run=await api('/agent/runs/'+run.id);if(scope)policy=await api('/policies/'+scope);health=await api('/health');recent=await api('/agent/runs');}
async function action(fn:()=>Promise<void>){if(busy)return;const saved=Array.from(document.querySelectorAll<HTMLInputElement|HTMLTextAreaElement|HTMLSelectElement>('input[id]:not([type=password]),textarea[id],select[id]')).map(x=>({id:x.id,value:x.value,checked:x instanceof HTMLInputElement?x.checked:false}));busy=true;notice='';isError=false;document.body.classList.add('busy');document.querySelectorAll<HTMLButtonElement>('button').forEach(b=>b.disabled=true);
 try{await fn();}catch(err){notice=explain(err instanceof Error?err.message:'SERVICE_UNAVAILABLE');isError=true;if(connected)try{await refresh();}catch{}}
 finally{busy=false;document.body.classList.remove('busy');render();if(isError)for(const x of saved){const el=document.getElementById(x.id) as HTMLInputElement|null;if(el){el.value=x.value;if(el.type==='checkbox')el.checked=x.checked;}}}}
function policySummary(){if(!policy)return '<div class="empty compact"><span class="eyebrow">POLICY</span><h3>정책부터 확인하세요</h3><p>연결 후 선택한 정책을<br>읽기 전용으로 표시합니다.</p></div>';
 const p=policy.policy,b=policy.balance;return `<div class="section-head"><h2>현재 정책</h2>${badge('읽기 전용')}</div><div class="policy-version"><span>버전 ${policy.version}</span><span>${e(p.currency)}</span></div><dl class="facts">${row('단일 거래 한도',money(p.maxPerTransaction))}${row('누적 예산 한도',money(p.maxBudget))}${row('모의 잔고',money(b?.balance))}${row('사용 / 예약',money(b?.spent)+'<br>'+money(b?.reserved))}${row('최소 잔여 금액',money(p.minimumRemaining))}${row('유효기간',e(date(p.validUntil)))}</dl><details><summary>전체 정책 확인</summary><dl class="facts">${row('허용 판매처',e(p.allowedMerchants.join(', ')||'제한 없음'))}${row('차단 판매처',e(p.blockedMerchants.join(', ')||'없음'))}${row('제외 브랜드',e(p.blockedBrands.join(', ')||'없음'))}${row('최소 평점',p.minimumReviewScore??'필수 아님')}${row('선호 기준',[p.preferLowerPrice?'낮은 가격':'',p.preferHigherReviewScore?'높은 평점':''].filter(Boolean).join(' · ')||'없음')}</dl><p class="muted">배송 속도는 확인된 근거가 없어 평가하지 않습니다.</p><p class="hash">정책 식별값 ${e(policy.digest)}</p></details><p class="footnote">거래 중 정책은 바뀌지 않습니다.<br>변경은 별도 정책 메뉴에서 가능합니다.</p>`;}
function requestForm(){return `<section class="surface"><div class="section-head"><div><span class="eyebrow">01 / REQUEST</span><h2>어떤 구매를 도와드릴까요?</h2></div>${badge('모의 주문','amber')}</div><form id="request-form"><fieldset${dis(!connected||run?.active||policy?.mode==='POLICY_EDIT')}><div class="track-choice"><label><input type="radio" name="track" value="Plan" checked><span><b>함께 계획하기</b><small>질문과 예시로 조건을 정합니다.</small></span></label><label><input type="radio" name="track" value="HardInput"><span><b>정한 조건으로 구매</b><small>명시한 조건과 일치해야 합니다.</small></span></label></div><label class="field" for="query"><span>구매할 내용</span><textarea id="query" rows="3" maxlength="600" required placeholder="필요한 품목과 용도, 꼭 지켜야 할 조건을 적어주세요."></textarea></label><div class="form-grid">${amount('maxTotal','최대 모의 금액 · '+e(policy?.policy.currency??'KRW'))}${field('quantity','수량','','number','min="1" max="100000"')}</div><details><summary>상품명을 정확히 지정하기</summary>${field('requiredName','정확히 일치해야 할 상품명','','text','maxlength="300"')}</details><div class="form-footer"><p class="muted">실제 결제와 배송은 발생하지 않습니다.</p><button class="primary" type="submit">구매 계획 시작 ↗</button></div></fieldset></form>${!connected?'<p class="inline-note">먼저 서비스에 연결해 주세요.</p>':''}${run?.active?'<p class="inline-note">현재 요청을 마치거나 취소한 뒤 새 요청을 시작할 수 있습니다.</p>':''}</section>`;}
function intentPanel(it:any){const q=it.quote,expired=new Date(it.expires_at).getTime()<=Date.now(),done=['COMMITTED','PROCESSING'].includes(it.state);return `<section class="final-review"><span class="eyebrow">03 / FINAL REVIEW</span><div class="section-head"><h3>최종 모의 주문 확인</h3>${badge(name(it.state),'amber')}</div><h2>${e(q.name)}</h2><dl class="facts">${row('수량',e(q.quantity)+'개')}${row('모의 단가',money(q.unitPrice,q.currency))}${row('모의 배송비',money(q.shipping,q.currency))}${row('합계',`<strong class="total">${money(q.total,q.currency)}</strong>`)}${row('유효기간',e(date(it.expires_at)))}</dl><p class="muted">사용자가 지정한 모의 금액 · 정책 v${run.policy_version}</p><p class="source">출처 ${e(q.sourceUrl)}</p>${done?'':expired?'<div class="callout warning"><p>견적이 만료됐습니다. 새 버전을 확인하고 다시 승인하세요.</p></div><button id="refresh-quote" class="secondary">견적 새로 확인</button>':`<label class="check"><input id="final-check" type="checkbox">품목·금액·정책을 확인했으며 모의 주문에 동의합니다.</label><button id="approve-purchase" class="primary"${dis(!health?.configured?.audit)}>모의 주문 승인 및 실행</button>${!health?.configured?.audit?'<p class="warning-text">감사 연결이 준비돼야 진행할 수 있습니다.</p>':''}`}</section>`;}
function runPanel(){
 if(!run)return '<section class="empty"><span class="step-number">02—04</span><h2>확인하고, 승인하고, 기록합니다.</h2><p>후보의 근거와 정책 판정을 확인한 뒤<br>직접 승인한 모의 주문만 실행합니다.</p></section>';
 const examples=run.evaluations.filter((x:any)=>x.kind==='EXAMPLE'),evaluations=run.evaluations.filter((x:any)=>x.kind==='EVALUATION'),approved=!!run.constraint_approval,it=run.intents.find((x:any)=>!['CANCELED','REJECTED'].includes(x.state));
 return `<section class="surface run-surface"><div class="section-head"><div><span class="eyebrow">CURRENT REQUEST</span><h2>${e(run.input.query)}</h2></div>${badge(name(run.state),run.error_code?'red':run.active?'amber':'green')}</div><ol class="progress"><li class="done">01 요청</li><li class="${run.constraints?'done':''}">02 조건 검토</li><li class="${it?'done':''}">03 최종 승인</li><li class="${run.receipts.length?'done':''}">04 기록</li></ol>${run.error_code?errorBox(run.error_code):''}
 ${run.question&&run.state==='NEEDS_INPUT'?`<div class="callout"><strong>추가로 확인할 내용</strong>${run.question.questions.map((q:string)=>`<p>${e(q)}</p>`).join('')}</div>`:''}
 ${run.active&&['READY','NEEDS_INPUT','ACTION_REQUIRED','CONSTRAINTS_DRAFT'].includes(run.state)?`<details${run.state==='NEEDS_INPUT'?' open':''}><summary>요청 내용 보완하기</summary><form id="answer-form"><label class="field" for="answer-query"><span>구매 내용과 답변</span><textarea id="answer-query" rows="3" maxlength="600" required>${e(run.input.query)}</textarea></label><div class="form-grid">${amount('answer-budget','최대 모의 금액',run.input.maxTotal??'')}${field('answer-quantity','수량',run.input.quantity??'','number','min="1" max="100000"')}</div>${field('answer-name','정확한 상품명 (선택)',run.input.requiredName??'')}<button class="secondary" type="submit">내용 저장</button><p class="muted">변경한 내용은 조건 승인을 다시 확인합니다.</p></form></details>`:''}
 ${run.constraints?`<div class="subsection"><div class="section-head"><h3>구매 조건</h3>${badge(approved?'검토 승인됨':'검토 필요',approved?'green':'amber')}</div><dl class="summary-grid">${row('검색 내용',e(run.constraints.query))}${row('최대 금액',money(run.constraints.maxTotal))}${row('수량',e(run.constraints.quantity)+'개')}${row('정확한 상품명',e(run.constraints.requiredName||'미지정'))}</dl><div class="evaluation-list">${[...examples,...evaluations].map((x:any)=>`<div class="evaluation">${badge(x.result.allowed?'허용':'반려',x.result.allowed?'green':'red')}<div><strong>${x.kind==='EXAMPLE'?'정책 예시':'후보 판정'} · ${money(x.result.total)}</strong><p>${x.result.allowed?'현재 정책 범위 안에 있습니다.':e(x.result.reasonCodes.map(explain).join(' '))}</p></div></div>`).join('')}</div>${!approved&&run.active?`<label class="check"><input id="constraints-check" type="checkbox">조건과 판정 결과를 확인했습니다.</label><button id="approve-constraints" class="primary"${dis(!(run.track==='Plan'?examples.length:evaluations.some((x:any)=>x.result.allowed)))}>구매 조건 승인</button>`:''}</div>`:''}
 <div class="subsection"><div class="section-head"><h3>검색 후보</h3><span class="muted">${run.candidates.length}개</span></div>${run.candidates.length?`<div class="candidate-list">${run.candidates.map((r:any)=>{const c=r.data;return `<label class="candidate"><input name="candidate" type="radio" value="${e(c.id)}"${selected===c.id?' checked':''}${dis(!run.active||it)}><div><strong>${e(c.fields?.name??c.name)}</strong><p class="source">${e(c.url)}</p><p>관찰 가격 ${e(c.fields?.observedPrice??'확인 불가')} ${e(c.fields?.currency??'')} · 평점 ${e(c.fields?.rating??'확인 불가')}</p>${c.sourceError?`<p class="warning-text">${e(explain(c.sourceError))}</p>`:''}<small>확인 시각 ${e(date(c.fetchedAt))} · 판매처 식별 ${c.verifiedMerchantHost?'검증됨':'미확인'}</small></div></label>`;}).join('')}</div>${run.active&&!it?`<form id="simulation-form"><h4>선택한 후보의 모의 금액</h4><p class="muted">직접 정하는 모의 입력이며 실제 판매처 견적이 아닙니다.</p><div class="form-grid">${amount('unitPrice','모의 단가','',true)}${amount('shipping','모의 배송비','',true)}</div><button class="secondary" type="submit">모의 금액 저장</button></form>`:''}`:'<div class="empty compact"><p>확인된 후보가 아직 없습니다.</p><small>검색 연결과 조건을 확인한 뒤 에이전트를 실행하세요.</small></div>'}</div>
 ${it?intentPanel(it):''}${run.receipts.length?'<div class="callout success"><strong>모의 영수증이 생성되었습니다.</strong><p>실제 주문·청구·배송은 없습니다. 감사 확정 여부를 별도로 확인하세요.</p><button id="show-receipts" class="secondary">영수증 확인</button></div>':''}
 <div class="run-actions"><button id="resume" class="primary"${dis(!run.active||['PROCESSING','AUDIT_PENDING','NEEDS_APPROVAL','NEEDS_INPUT'].includes(run.state))}>${run.error_code?'연결 확인 후 재시도':'에이전트 계속 실행'}</button><button id="refresh" class="secondary">상태 새로고침</button><button id="cancel" class="text-button danger"${dis(!run.active||run.state==='AUDIT_PENDING')}>요청 취소</button></div><details class="reference"><summary>요청 식별 정보</summary><p class="hash">${e(run.id)}</p><p class="muted">정책 v${run.policy_version} · ${e(date(run.created_at))}</p></details></section>`;
}
function policyPage(){const p=policy?.policy;if(!p)return '<section class="empty"><h2>연결 후 정책을 확인할 수 있습니다.</h2></section>';return `<section class="surface"><div class="section-head"><div><span class="eyebrow">POLICY SETTINGS</span><h2>정책 변경</h2></div>${badge(edit?'편집 중':'읽기 전용',edit?'amber':'neutral')}</div><p class="lead">발행한 정책을 보존하고, 승인한 변경 사항을 새 버전으로 만듭니다.</p>${policy.busy?errorBox('POLICY_BUSY'):''}${!health?.capabilities?.policyAdmin?errorBox('POLICY_ADMIN_UNAVAILABLE'):''}
 ${!edit?`<button id="enter-edit" class="primary"${dis(policy.busy||policy.mode==='POLICY_EDIT'||!health?.capabilities?.policyAdmin)}>새 정책 버전 작성</button>${policy.mode==='POLICY_EDIT'?'<p class="warning-text">다른 화면에서 시작한 정책 편집이 있습니다.</p><button id="restore-edit" class="secondary">편집 세션 열기</button>':''}<div class="policy-readonly">${policySummary()}</div>`:`<form id="policy-form"><div class="form-grid"><label class="field" for="policy-currency"><span>통화</span><select id="policy-currency">${Array.from(new Set([p.currency,...Intl.supportedValuesOf('currency')])).map(c=>`<option${c===p.currency?' selected':''}>${e(c)}</option>`).join('')}</select></label>${field('policy-until','유효기간',new Date(new Date(p.validUntil).getTime()-new Date(p.validUntil).getTimezoneOffset()*60000).toISOString().slice(0,16),'datetime-local','required')}</div><p class="muted">금액은 최소 통화 단위 정수입니다. KRW는 원, USD·EUR는 센트 단위입니다.</p><div class="form-grid">${amount('policy-budget','누적 예산 한도',p.maxBudget,true)}${amount('policy-transaction','단일 거래 한도',p.maxPerTransaction,true)}${amount('policy-remaining','최소 잔여 금액',p.minimumRemaining,true)}${field('policy-review','최소 리뷰 평점 (선택)',p.minimumReviewScore??'','number','min="0" max="5" step="0.1"')}</div><div class="callout"><p>KRW 외 통화·리뷰 필수 정책은 현재 감사 v1 미지원입니다. 판매처 제한은 검증된 어댑터가 없으면 구매를 차단합니다.</p></div>${field('policy-allow','허용 판매처 (쉼표로 구분)',p.allowedMerchants.join(', '))}${field('policy-block','차단 판매처 (쉼표로 구분)',p.blockedMerchants.join(', '))}${field('policy-brands','제외 브랜드 (쉼표로 구분)',p.blockedBrands.join(', '))}<h3>허용 후보의 선호 기준</h3><label class="check"><input id="policy-price" type="checkbox"${p.preferLowerPrice?' checked':''}>낮은 가격 우선</label><label class="check"><input id="policy-rating" type="checkbox"${p.preferHigherReviewScore?' checked':''}>높은 평점 우선</label><p class="muted">둘 다 선택하면 가격, 평점 순입니다. 배송 속도는 근거 수집 미지원입니다.</p><div class="form-footer"><label class="check"><input id="policy-consent" type="checkbox" required>변경 내용과 새 버전 발행에 동의합니다.</label><button class="primary" type="submit">정책 v${policy.version+1} 발행</button><button id="cancel-edit" type="button" class="secondary">편집 취소</button></div></form>`}</section>`;}
function historyPage(){return `<section class="surface"><div class="section-head"><div><span class="eyebrow">RECEIPTS</span><h2>모의 주문 기록</h2></div><button id="reload-history" class="secondary"${dis(!connected)}>새로고침</button></div><p class="lead">모의 주문 확정과 실제 Sepolia 감사 확정을 구분합니다.</p>${history.length?history.map(r=>`<button class="receipt-row" data-receipt="${e(r.id)}"><span><strong>${e(r.data.quote.name)}</strong><small>${e(date(r.created_at))}</small></span><span>${money(r.data.quote.total,r.data.quote.currency)} ${badge('모의 영수증')}</span><span aria-hidden="true">↗</span></button>`).join(''):'<div class="empty"><span class="step-number">—</span><h3>아직 모의 영수증이 없습니다.</h3><p>직접 승인한 주문이 처리되면 여기에 표시됩니다.</p></div>'}${receipt?`<div class="subsection"><h3>${e(receipt.quote.name)} ${badge('SIMULATION','amber')}</h3><dl class="facts">${row('합계',money(receipt.quote.total,receipt.quote.currency))}${row('정책','v'+e(receipt.policyVersion))}${row('감사 상태',e(name(audit?.state??'PENDING')))}</dl><p>실제 주문·청구·배송이 없는 모의 영수증입니다.</p>${audit?.report?.txHash?`<p class="hash">트랜잭션 ${e(audit.report.txHash)}</p><p>검증 ${e(audit.report.verification)} · 확정 ${e(audit.report.finality)}</p>`:'<p class="warning-text">확인된 온체인 기록이 아직 없습니다.</p>'}</div>`:''}</section>`;}
function render(){app.innerHTML=`<div class="app-shell"><aside class="sidebar"><div class="brand"><span class="brand-mark">11</span><span>구매 작업실<small>TEAM 11</small></span></div><div class="workspace-label">WORKSPACE</div><nav aria-label="주 메뉴">${[['purchase','구매 계획','01'],['policy','정책 관리','02'],['history','주문 기록','03']].map(([id,t,n])=>`<button data-page="${id}" class="nav-item ${page===id?'active':''}" aria-current="${page===id?'page':'false'}"${dis(id==='policy'&&policy?.busy)}><span>${n}</span>${t}</button>`).join('')}</nav><div class="sidebar-bottom"><span class="live-dot"></span> 모의 주문 환경<p>실제 결제·배송 없음<br>감사는 Sepolia에 별도 기록</p><button id="open-connection" class="sidebar-link">연결 설정</button></div></aside><div class="workspace"><header class="topbar"><div><span class="eyebrow">PURCHASE WORKSPACE</span><h1>${page==='purchase'?'구매 계획':page==='policy'?'정책 관리':'주문 기록'}</h1></div><div class="top-actions">${badge('SIMULATION','amber')}<button id="connection-toggle" class="connection-button"><span class="live-dot ${connected?'':'off'}"></span>${connected?'연결됨':'서비스 연결'}</button></div></header><div class="simulation-strip"><span>모의 주문 안내</span>실제 주문·청구·배송은 없습니다. 감사는 별도의 실제 Sepolia 트랜잭션입니다.</div>${notice?`<div role="${isError?'alert':'status'}" class="notification ${isError?'error':''}">${e(notice)}</div>`:''}
 ${connectionOpen?`<section class="connection-panel surface"><div><h2>작업 공간 연결</h2><p class="muted">토큰은 화면 메모리에만 보관합니다.<br>Kiln API 키를 입력하는 곳이 아닙니다.</p></div><form id="connect-form">${field('token','개인 접근 토큰','','password','autocomplete="off" required')}<button class="primary" type="submit">연결하기</button>${connected?'<button id="disconnect" type="button" class="secondary">연결 해제</button>':''}</form></section>`:''}
 ${connected?`<div class="scope-bar"><label for="scope">정책 범위</label><select id="scope"${dis(run?.active||edit)}>${scopes.map(s=>`<option value="${e(s.id)}"${s.id===scope?' selected':''}>${e(s.id)}</option>`).join('')}</select><div class="connections">${[['kiln','에이전트'],['search','검색'],['audit','감사']].map(([k,t])=>`<span class="${health?.configured?.[k]?'':'warning-text'}">${health?.configured?.[k]?'●':'○'} ${t} ${health?.configured?.[k]?(k==='audit'?'준비됨':'설정됨'):'연결 필요'}</span>`).join('')}</div></div>`:''}
 <main>${page==='purchase'?`<div class="page-intro"><div><span class="eyebrow">DECIDE WITH CONFIDENCE</span><h2>필요한 구매에,<br><em>명확한 기준을.</em></h2></div><p>조건을 정하고 근거를 검토하세요.<br>마지막 결정은 언제나 직접 합니다.</p></div><div class="content-grid"><div>${requestForm()}${runPanel()}${recent.length?`<details class="recent surface"><summary>이전 요청 불러오기</summary>${recent.map(r=>`<button data-run="${e(r.id)}" class="recent-row"><span>${e(r.input.query)}</span>${badge(name(r.state))}</button>`).join('')}</details>`:''}</div><aside class="policy-rail surface ${policyExpanded?'expanded':''}"><button id="policy-expand" class="policy-expand" aria-expanded="${policyExpanded}">현재 정책 확인 <span>${policyExpanded?'−':'+'}</span></button><div class="policy-content">${policySummary()}</div></aside></div>`:page==='policy'?policyPage():historyPage()}</main><footer>TEAM 11 <span>모든 주문은 시뮬레이션입니다.</span></footer></div></div>`;bind();}
function on(id:string,fn:()=>Promise<void>){document.getElementById(id)?.addEventListener('click',()=>void action(fn));}
function form(id:string,fn:()=>Promise<void>){document.getElementById(id)?.addEventListener('submit',ev=>{ev.preventDefault();void action(fn);});}
function canonical(v:any):string{return Array.isArray(v)?'['+v.map(canonical).join(',')+']':v&&typeof v==='object'?'{'+Object.keys(v).sort().map(k=>JSON.stringify(k)+':'+canonical(v[k])).join(',')+'}':JSON.stringify(v);}
async function answer(payload:any){await api('/agent/runs/'+run.id+'/events','POST',{eventId:crypto.randomUUID(),expectedVersion:run.version,type:'ANSWER',payload});await refresh();}
function bind(){
 on('policy-expand',async()=>{policyExpanded=!policyExpanded;});
 for(const id of ['connection-toggle','open-connection'])on(id,async()=>{connectionOpen=!connectionOpen;});
 form('connect-form',async()=>{token=value('token');health=await api('/health');scopes=await api('/scopes');connected=true;scope=scopes[0]?.id??'';connectionOpen=false;await refresh();});
 on('disconnect',async()=>{token='';connected=false;run=null;policy=null;scopes=[];recent=[];history=[];edit=null;connectionOpen=true;});
 document.querySelectorAll<HTMLButtonElement>('[data-page]').forEach(b=>b.addEventListener('click',()=>void action(async()=>{if(edit&&b.dataset.page!==page)throw Error('POLICY_BUSY');page=b.dataset.page!;window.scrollTo(0,0);if(page==='history'&&connected)history=await api('/receipts');if(connected)await refresh();})));
 document.getElementById('scope')?.addEventListener('change',()=>void action(async()=>{scope=value('scope');run=null;await refresh();}));
 form('request-form',async()=>{if(!connected)throw Error('UNAUTHORIZED');const track=(document.querySelector('input[name="track"]:checked') as HTMLInputElement).value,input:any={query:value('query')};if(value('maxTotal'))input.maxTotal=value('maxTotal');if(value('quantity'))input.quantity=Number(value('quantity'));if(value('requiredName'))input.requiredName=value('requiredName');if(track==='HardInput'&&(!input.maxTotal||!input.quantity))throw Error('INVALID_INPUT');const r=await api('/agent/runs','POST',{scopeId:scope,track,input});run={id:r.runId};selected='';await refresh();});
 on('resume',async()=>{await api('/agent/runs/'+run.id+'/resume','POST',{});await refresh();});on('refresh',refresh);
 form('answer-form',async()=>{const p:any={query:value('answer-query')};if(value('answer-budget'))p.maxTotal=value('answer-budget');if(value('answer-quantity'))p.quantity=Number(value('answer-quantity'));if(value('answer-name'))p.requiredName=value('answer-name');await answer(p);});
 document.querySelectorAll<HTMLInputElement>('input[name="candidate"]').forEach(r=>r.addEventListener('change',()=>{selected=r.value;}));
 form('simulation-form',async()=>{if(!selected)throw Error('SIMULATION_INPUT_REQUIRED');await answer({simulation:{candidateId:selected,unitPrice:value('unitPrice'),shipping:value('shipping')}});});
 on('approve-constraints',async()=>{if(!check('constraints-check'))throw Error('CONSTRAINT_APPROVAL_REQUIRED');const ids=run.evaluations.filter((x:any)=>run.track==='Plan'?x.kind==='EXAMPLE':x.kind==='EVALUATION'&&x.result.allowed).slice(0,run.track==='Plan'?2:20).map((x:any)=>x.id);await api('/agent/runs/'+run.id+'/constraint-approvals','POST',{constraintVersion:run.constraint_version,policyDigest:run.policy_digest,trackEvidenceIds:ids});await refresh();});
 on('cancel',async()=>{await api('/agent/runs/'+run.id+'/events','POST',{eventId:crypto.randomUUID(),expectedVersion:run.version,type:'CANCEL',payload:{}});await refresh();});
 const it=run?.intents?.find((x:any)=>!['CANCELED','REJECTED'].includes(x.state));
 on('refresh-quote',async()=>{await api('/purchase-intents/'+it.id+'/refresh','POST',{});await refresh();});
 on('approve-purchase',async()=>{if(!check('final-check'))throw Error('PURCHASE_APPROVAL_REQUIRED');await api('/purchase-intents/'+it.id+'/approvals','POST',{quoteVersion:it.quote_version,expectedGeneration:it.generation,mode:'SIMULATION',requestKey:crypto.randomUUID()});await refresh();await api('/agent/runs/'+run.id+'/resume','POST',{});await refresh();});
 for(const id of ['show-receipts','reload-history'])on(id,async()=>{page='history';history=await api('/receipts');});
 document.querySelectorAll<HTMLButtonElement>('[data-receipt]').forEach(b=>b.addEventListener('click',()=>void action(async()=>{receipt=await api('/receipts/'+b.dataset.receipt);audit=await api('/receipts/'+b.dataset.receipt+'/audit');})));
 document.querySelectorAll<HTMLButtonElement>('[data-run]').forEach(b=>b.addEventListener('click',()=>void action(async()=>{if(run?.active&&run.id!==b.dataset.run)throw Error('RUN_BUSY');run=await api('/agent/runs/'+b.dataset.run);scope=run.scope_id;await refresh();})));
 on('restore-edit',async()=>{edit={editId:policy.edit_id,baseVersion:policy.edit_base};});
 on('enter-edit',async()=>{edit=await api('/policy-edit-sessions','POST',{scopeId:scope});await refresh();});
 on('cancel-edit',async()=>{await api('/policy-edit-sessions/'+edit.editId,'DELETE',{scopeId:scope});edit=null;await refresh();});
 form('policy-form',async()=>{if(!check('policy-consent'))throw Error('INVALID_INPUT');const currency=value('policy-currency'),list=(id:string)=>value(id).split(',').map(s=>s.trim()).filter(Boolean),draft={...policy.policy,currency,minorDigits:new Intl.NumberFormat('en',{style:'currency',currency}).resolvedOptions().maximumFractionDigits,maxBudget:value('policy-budget'),maxPerTransaction:value('policy-transaction'),minimumRemaining:value('policy-remaining'),validUntil:new Date(value('policy-until')).toISOString(),allowedMerchants:list('policy-allow'),blockedMerchants:list('policy-block'),blockedBrands:list('policy-brands'),minimumReviewScore:value('policy-review')?Number(value('policy-review')):null,preferLowerPrice:check('policy-price'),preferHigherReviewScore:check('policy-rating')};const hash=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(canonical(draft)));await api('/policy-edit-sessions/'+edit.editId+'/publish','POST',{scopeId:scope,baseVersion:edit.baseVersion,draft,approvedDigest:Array.from(new Uint8Array(hash),x=>x.toString(16).padStart(2,'0')).join('')});edit=null;await refresh();notice='새 정책 버전을 발행했습니다.';});
}
render();
setInterval(()=>{if(connected&&!busy&&run?.active&&['PROCESSING','AUDIT_PENDING'].includes(run.state))void action(refresh);},10000);
