import {accountEmail} from './account-id';
import {activitySteps,transactionLink} from './activity';
import {icon,guestHome,emptyState} from './ui';
import {mountAppControls} from './pwa';
import {startTutorial,tutorialOpen} from './tutorial';
import {authClient} from './auth';
import {authPage,signupEnabled} from './auth-page';
import '@fontsource/ibm-plex-mono/latin-400.css';
import '@fontsource/ibm-plex-sans-kr/400.css';
import '@fontsource/ibm-plex-sans-kr/600.css';
import '../../opendesign/design-systems/franchise-procurement/tokens/colors_and_type.css';





import './app.css';
import {explain,stateNames} from './messages';
const app=document.querySelector<HTMLDivElement>('#app')!;

let renderedView='';
let audits:any[]=[],wallet:any=null,agentWorking=false;
let token='',connected=false,health:any=null,policy:any=null,run:any=null,edit:any=null;
let scopes:any[]=[],history:any[]=[],recent:any[]=[],audit:any=null,receipt:any=null;
let page='purchase',scope='',policyExpanded=false,busy=false,notice='',isError=false,selected='',showSetup=false;
const e=(v:any)=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const name=(s:string)=>stateNames[s]??s;
const value=(id:string)=>(document.getElementById(id) as HTMLInputElement)?.value??'';
const check=(id:string)=>(document.getElementById(id) as HTMLInputElement)?.checked??false;
const dis=(v:any)=>v?' disabled':'';
const date=(v:any)=>v?new Date(v).toLocaleString('ko-KR',{timeZone:'Asia/Seoul'}):'—';
function money(v:any,c=policy?.policy.currency??'KRW',d=policy?.policy.minorDigits??0){
 if(v==null)return '확인 필요';try{const n=BigInt(v),b=10n**BigInt(d);return (n/b).toLocaleString('ko-KR')+(d?'.'+String(n%b).padStart(d,'0'):'')+' '+c;}catch{return '확인 필요';}
}
const badge=(s:string,k='neutral')=>`<span class="badge ${k}">${e(s)}</span>`;
const field=(id:string,title:string,v:any='',type='text',extra='')=>`<label class="field" for="${id}"><span>${title}</span><input id="${id}" type="${type}" value="${e(v)}" ${extra}></label>`;
const amount=(id:string,title:string,v:any='',required=false)=>field(id,title,v,'text',`inputmode="numeric" pattern="[0-9]+" maxlength="15" data-amount ${required?'required':''}`);
const row=(title:string,v:any)=>`<div><dt>${title}</dt><dd>${v}</dd></div>`;
const errorBox=(code:string)=>`<div class="callout warning"><strong>확인이 필요합니다</strong><p>${e(explain(code))}</p><small>오류 코드 · ${e(code)}</small></div>`;
async function api(url:string,method='GET',body?:unknown){
 if(!navigator.onLine)throw Error('SERVICE_UNAVAILABLE');
 if(authClient){const {data}=await authClient.auth.getSession();token=data.session?.access_token??'';}
 let res:Response;try{res=await fetch('/api'+url,{method,headers:{'Content-Type':'application/json',...(token?{Authorization:'Bearer '+token}:{})},...(body===undefined?{}:{body:JSON.stringify(body)})});}catch{throw Error('SERVICE_UNAVAILABLE');}
 let data:any;try{data=res.headers.get('content-type')?.includes('application/json')?await res.json():null;}catch{data=null;}
 if(!res.ok||!data)throw Error(data?.error??(url.startsWith('/policy-edit')?'POLICY_ADMIN_UNAVAILABLE':'SERVICE_UNAVAILABLE'));return data;
}
async function refresh(){if(run)run=await api('/agent/runs/'+run.id);if(scope)policy=await api('/policies/'+scope);health=await api(connected?'/audit/status':'/health');recent=await api('/agent/runs');}
async function loadAccount(){audits=[];wallet=null;receipt=null;audit=null;history=[];run=null;selected='';health=await api('/health');scopes=await api('/scopes');connected=true;scope=scopes[0]?.id??'';await refresh();const active=recent.find(r=>r.active);if(active){run=await api('/agent/runs/'+active.id);scope=run.scope_id;await refresh();}}
function setupPanel(){return `<section class="surface"><h2>정책 추가하기</h2><form id="setup-form">${amount('setup-budget','예산 한도 · 원','',true)}<p class="muted">기본값: KRW · 1회 한도와 모의 잔고는 예산과 같음 · 1년 유효</p><details><summary>세부 조건</summary><div class="form-grid">${amount('setup-transaction','1회 거래 한도 · 원')}${amount('setup-remaining','남겨둘 금액 · 원')}${field('setup-until','유효기간','','datetime-local')}${amount('setup-balance','모의 잔고 · 원')}</div>${field('setup-allow','허용 판매처 (쉼표로 구분)')}${field('setup-block','차단 판매처 (쉼표로 구분)')}${field('setup-brands','제외 브랜드 (쉼표로 구분)')}${field('setup-review','최소 평점 (선택)','','number','min="0" max="5" step="0.1"')}</details><label class="check"><input id="setup-consent" type="checkbox" required>정책을 확인하고 저장합니다.</label><button class="primary" type="submit">정책 저장</button></form></section>`;}
async function action(fn:()=>Promise<void>){if(busy)return;const focusedId=(document.activeElement as HTMLElement)?.id;const saved=Array.from(document.querySelectorAll<HTMLInputElement|HTMLTextAreaElement|HTMLSelectElement>('input[id]:not([type=password]),textarea[id],select[id]')).map(x=>({id:x.id,value:x.value,checked:x instanceof HTMLInputElement?x.checked:false}));busy=true;notice='';isError=false;document.body.classList.add('busy');document.querySelectorAll<HTMLButtonElement>('button').forEach(b=>b.disabled=true);
 try{await fn();}catch(err){notice=explain(err instanceof Error?err.message:'SERVICE_UNAVAILABLE');isError=true;if(connected)try{await refresh();}catch{}}
 finally{busy=false;document.body.classList.remove('busy');render();const focusTarget=(focusedId?document.getElementById(focusedId):null)??app.querySelector<HTMLElement>('h1');if(focusTarget){if(focusTarget.tagName==='H1')focusTarget.tabIndex=-1;focusTarget.focus({preventScroll:true});}if(isError)for(const x of saved){const el=document.getElementById(x.id) as HTMLInputElement|null;if(el){el.value=x.value;if(el.type==='checkbox')el.checked=x.checked;}}}}
function policySummary(){if(!policy)return '<div class="empty compact"><p>아직 정책이 없습니다.</p></div>';
 const p=policy.policy,b=policy.balance;return `<div class="section-head"><h2>현재 정책</h2>${badge('읽기 전용')}</div><div class="policy-version"><span>버전 ${policy.version}</span><span>${e(p.currency)}</span></div><dl class="facts">${row('단일 거래 한도',money(p.maxPerTransaction))}${row('누적 예산 한도',money(p.maxBudget))}${row('모의 잔고',money(b?.balance))}${row('사용 / 예약',money(b?.spent)+'<br>'+money(b?.reserved))}${row('최소 잔여 금액',money(p.minimumRemaining))}${row('유효기간',e(date(p.validUntil)))}</dl><details><summary>전체 정책 확인</summary><dl class="facts">${row('허용 판매처',e(p.allowedMerchants.join(', ')||'제한 없음'))}${row('차단 판매처',e(p.blockedMerchants.join(', ')||'없음'))}${row('제외 브랜드',e(p.blockedBrands.join(', ')||'없음'))}${row('최소 평점',p.minimumReviewScore??'필수 아님')}${row('선호 기준',[p.preferLowerPrice?'낮은 가격':'',p.preferHigherReviewScore?'높은 평점':''].filter(Boolean).join(' · ')||'없음')}</dl><p class="muted">배송 속도는 확인된 근거가 없어 평가하지 않습니다.</p><p class="hash">정책 식별값 ${e(policy.digest)}</p></details>`;}
function requestForm(){return `<section class="surface request-surface"><h2>무엇을 찾으세요?</h2><form id="request-form"><fieldset${dis(!connected||!scope||run?.active||policy?.mode==='POLICY_EDIT')}><label class="field" for="query"><span>요청</span><textarea id="query" rows="3" maxlength="600" required placeholder="원하는 상품과 예산을 적어주세요"></textarea></label><details><summary>조건 추가</summary><div class="track-choice"><label><input type="radio" name="track" value="Plan" checked><span>함께 계획</span></label><label><input type="radio" name="track" value="HardInput"><span>조건 고정</span></label></div><div class="form-grid">${amount('maxTotal','최대 금액 · '+e(policy?.policy.currency??'KRW'))}${field('quantity','수량','','number','min="1" max="100000"')}</div>${field('requiredName','정확한 상품명','','text','maxlength="300"')}<label class="check"><input id="auto-purchase" type="checkbox">조건에 맞는 상품을 찾으면 모의 주문 자동 확정</label><p class="muted">자동 확정은 조건 고정·최대 금액·수량·정확한 상품명을 입력한 경우에만 가능합니다. 실제 결제는 없으며 대납 모드가 연결되면 서비스가 Sepolia 감사 가스를 부담합니다.</p></details><button class="primary" type="submit">검색 시작 ${icon('next',20)}</button></fieldset></form></section>`;}
function intentPanel(it:any){const q=it.quote,expired=new Date(it.expires_at).getTime()<=Date.now(),done=['COMMITTED','PROCESSING'].includes(it.state);return `<section class="final-review"><div class="section-head"><h3>최종 모의 주문 확인</h3>${badge(name(it.state),'amber')}</div><h2>${e(q.name)}</h2><dl class="facts">${row('수량',e(q.quantity)+'개')}${row('확인한 단가',money(q.unitPrice,q.currency))}${row('확인한 배송비',money(q.shipping,q.currency))}${row('합계',`<strong class="total">${money(q.total,q.currency)}</strong>`)}${row('가격 확인 시각',e(date(q.fetchedAt)))}</dl><p class="muted">판매 페이지 관측 가격 · 정책 v${run.policy_version} · 주문만 시뮬레이션</p><p class="source">출처 ${e(q.sourceUrl)}</p>${done?'':expired?'<div class="callout warning"><p>견적이 만료됐습니다. 새 검색이 필요합니다.</p></div>':`<label class="check"><input id="final-check" type="checkbox">품목·금액·정책을 확인했으며 모의 주문에 동의합니다.</label><button id="approve-purchase" class="primary"${dis(!health?.configured?.audit)}>모의 주문 승인 및 실행</button>${!health?.configured?.audit?'<p class="warning-text">'+e(explain('AUDIT_NOT_READY'))+'</p>':''}`}</section>`;}
function runPanel(){
 if(!run)return '';
 const examples=run.evaluations.filter((x:any)=>x.kind==='EXAMPLE'),evaluations=run.evaluations.filter((x:any)=>x.kind==='EVALUATION'),approved=!!run.constraint_approval,it=run.intents.find((x:any)=>!['CANCELED','REJECTED'].includes(x.state));
 const hasReceipt=run.receipts.length>0,finalApproved=!!it&&['READY_FOR_TOOL','PROCESSING','AUDIT_PENDING','COMPLETED','COMMITTED'].includes(it.state),currentStep=hasReceipt?-1:!run.constraints?0:!approved?1:finalApproved?3:2;
 const progress=(index:number,label:string)=>{const status=hasReceipt||index<currentStep?'done':index===currentStep?'current':'';return `<li class="${status}"${status==='current'?' aria-current="step"':''}>${label}</li>`;};
 return `<section class="surface run-surface"><div class="section-head"><div><h2>${e(run.input.query)}</h2></div>${badge(name(run.state),run.error_code?'red':run.active?'amber':'green')}</div><ol class="progress" aria-label="구매 요청 진행 단계">${progress(0,'01 요청')}${progress(1,'02 조건 검토')}${progress(2,'03 최종 승인')}${progress(3,'04 기록')}</ol>${run.error_code?errorBox(run.error_code):''}<div id="agent-activity" class="agent-activity" role="status" aria-live="polite">${activityPanel()}</div>
 ${run.question&&run.state==='NEEDS_INPUT'?`<div class="callout"><strong>추가로 확인할 내용</strong>${run.question.questions.map((q:string)=>`<p>${e(run.question.questionKey==='source_price'?'현재 검색 결과는 가격 또는 배송비가 확인되지 않아 구매 계산을 할 수 없습니다. 다른 상품명으로 다시 검색해 주세요.':q)}</p>`).join('')}</div>`:''}
 ${run.active&&['READY','NEEDS_INPUT','ACTION_REQUIRED','CONSTRAINTS_DRAFT'].includes(run.state)?`<details${run.state==='NEEDS_INPUT'?' open':''}><summary>검색 내용 바꾸기</summary><form id="answer-form"><label class="field" for="answer-query"><span>다시 찾을 상품</span><textarea id="answer-query" rows="3" maxlength="600" required>${e(run.input.query)}</textarea></label><details><summary>금액·수량 조정</summary><p class="muted answer-hint">바꾸려는 값만 입력하세요. 비워 둔 조건은 그대로 유지됩니다.</p><div class="form-grid">${amount('answer-budget','최대 금액 (선택)',run.input.maxTotal??'')}${field('answer-quantity','수량 (선택)',run.input.quantity??'','number','min="1" max="100000"')}</div>${field('answer-name','정확한 상품명 (선택)',run.input.requiredName??'')}</details><button class="primary" type="submit">다시 검색</button></form></details>`:''}
 ${run.constraints?`<div class="subsection"><div class="section-head"><h3>구매 조건</h3>${badge(approved?'검토 승인됨':'검토 필요',approved?'green':'amber')}</div><dl class="summary-grid">${row('검색 내용',e(run.constraints.query))}${row('최대 금액',money(run.constraints.maxTotal))}${row('수량',e(run.constraints.quantity)+'개')}${row('정확한 상품명',e(run.constraints.requiredName||'미지정'))}</dl><div class="evaluation-list">${[...examples,...evaluations].map((x:any)=>`<div class="evaluation">${badge(x.result.allowed?'허용':'반려',x.result.allowed?'green':'red')}<div><strong>${x.kind==='EXAMPLE'?'정책 예시':'후보 판정'} · ${money(x.result.total)}</strong><p>${x.result.allowed?'현재 정책 범위 안에 있습니다.':e(x.result.reasonCodes.map(explain).join(' '))}</p></div></div>`).join('')}</div>${!approved&&run.active?`<label class="check"><input id="constraints-check" type="checkbox">조건과 판정 결과를 확인했습니다.</label><button id="approve-constraints" class="primary"${dis(!(run.track==='Plan'?examples.length:evaluations.some((x:any)=>x.result.allowed)))}>구매 조건 승인</button>`:''}</div>`:''}
 <div class="subsection"><div class="section-head"><h3>상품 검색 결과</h3><span class="muted">${run.candidates.length}개</span></div>${run.candidates.length?`<div class="candidate-list">${run.candidates.map((r:any)=>{const c=r.data,f=c.fields??{};return `<article class="candidate-card"><span class="candidate-icon">${icon('bag',24)}</span><div><strong>${e(f.name??c.name)}</strong><p class="candidate-meta">판매 페이지 가격 ${e(f.observedPrice??'확인 불가')} ${e(f.currency??'')} · 배송비 ${e(f.observedShipping??'확인 불가')} ${e(f.shippingCurrency??'')}</p><small>${e(c.verifiedMerchantHost??'출처 확인 불가')} · ${e(date(c.fetchedAt))}${Date.now()-new Date(c.fetchedAt).getTime()>300000?' · 다시 검색 필요':''}</small><details class="source-detail"><summary>가격 근거</summary><a class="source" href="${e(c.url)}" target="_blank" rel="noopener noreferrer">판매 페이지 열기</a>${c.sourceError?`<p class="warning-text">${e(explain(c.sourceError))}</p>`:''}</details></div></article>`;}).join('')}</div>`:'<div class="empty compact"><p>가격이 확인된 판매 페이지를 찾지 못했습니다.</p></div>'}</div>
 ${it?intentPanel(it):''}${run.receipts.length?'<div class="callout success"><strong>모의 영수증이 생성되었습니다.</strong><p>실제 주문·청구·배송은 없습니다. 감사 확정 여부를 별도로 확인하세요.</p><button id="show-receipts" class="secondary">영수증 확인</button><button id="show-settings" class="secondary">트랜잭션 확인</button></div>':''}
 <div class="run-actions">${run.active&&['READY','ACTION_REQUIRED'].includes(run.state)?`<button id="resume" class="secondary">검색 재시도</button>`:''}${run.active&&run.state!=='AUDIT_PENDING'?`<details><summary>요청 관리</summary><button id="cancel" class="text-button danger">요청 취소</button></details>`:''}</div><div class="reference"><small>요청 ID</small><p class="hash">${e(run.id)}</p><p class="muted">정책 v${run.policy_version} · ${e(date(run.created_at))}</p></div></section>`;
}
function policyPage(){const p=policy?.policy;if(!p)return showSetup?setupPanel():`<section class="surface"><h2>구매 정책</h2><p>아직 정책이 없습니다.</p><button id="add-policy" class="primary">정책 추가하기</button></section>`;return `<section class="surface"><div class="section-head"><div><h2>정책 변경</h2></div>${badge(edit?'편집 중':'읽기 전용',edit?'amber':'neutral')}</div>${policy.busy?errorBox('POLICY_BUSY'):''}${!health?.capabilities?.policyAdmin?errorBox('POLICY_ADMIN_UNAVAILABLE'):''}
 ${!edit?`<button id="enter-edit" class="primary"${dis(policy.busy||policy.mode==='POLICY_EDIT'||!health?.capabilities?.policyAdmin)}>새 정책 버전 작성</button>${policy.mode==='POLICY_EDIT'?'<p class="warning-text">다른 화면에서 시작한 정책 편집이 있습니다.</p><button id="restore-edit" class="secondary">편집 세션 열기</button>':''}<div class="policy-readonly">${policySummary()}</div>`:`<form id="policy-form"><div class="form-grid"><label class="field" for="policy-currency"><span>통화</span><select id="policy-currency">${Array.from(new Set([p.currency,...Intl.supportedValuesOf('currency')])).map(c=>`<option${c===p.currency?' selected':''}>${e(c)}</option>`).join('')}</select></label>${field('policy-until','유효기간',new Date(new Date(p.validUntil).getTime()-new Date(p.validUntil).getTimezoneOffset()*60000).toISOString().slice(0,16),'datetime-local','required')}</div><p class="muted">금액은 최소 통화 단위 정수입니다. KRW는 원, USD·EUR는 센트 단위입니다.</p><div class="form-grid">${amount('policy-budget','누적 예산 한도',p.maxBudget,true)}${amount('policy-transaction','단일 거래 한도',p.maxPerTransaction,true)}${amount('policy-remaining','최소 잔여 금액',p.minimumRemaining,true)}${field('policy-review','최소 리뷰 평점 (선택)',p.minimumReviewScore??'','number','min="0" max="5" step="0.1"')}</div><div class="callout"><p>KRW 외 통화·리뷰 필수 정책은 현재 감사 v1 미지원입니다. 판매처 제한은 검증된 어댑터가 없으면 구매를 차단합니다.</p></div>${field('policy-allow','허용 판매처 (쉼표로 구분)',p.allowedMerchants.join(', '))}${field('policy-block','차단 판매처 (쉼표로 구분)',p.blockedMerchants.join(', '))}${field('policy-brands','제외 브랜드 (쉼표로 구분)',p.blockedBrands.join(', '))}<h3>허용 후보의 선호 기준</h3><label class="check"><input id="policy-price" type="checkbox"${p.preferLowerPrice?' checked':''}>낮은 가격 우선</label><label class="check"><input id="policy-rating" type="checkbox"${p.preferHigherReviewScore?' checked':''}>높은 평점 우선</label><p class="muted">둘 다 선택하면 가격, 평점 순입니다. 배송 속도는 근거 수집 미지원입니다.</p><div class="form-footer"><label class="check"><input id="policy-consent" type="checkbox" required>변경 내용과 새 버전 발행에 동의합니다.</label><button class="primary" type="submit">정책 v${policy.version+1} 발행</button><button id="cancel-edit" type="button" class="secondary">편집 취소</button></div></form>`}</section>`;}
function historyPage(){if(!recent.length&&!history.length&&!receipt)return emptyState('history',connected);const detailLink=transactionLink(audit?.report);return `<section class="surface"><h2>요청 기록</h2>${recent.map(r=>`<button data-run="${e(r.id)}" class="recent-row"><span>${e(r.input.query)}<small>${e(date(r.created_at))}</small></span>${badge(name(r.state))}</button>`).join('')||'<p>아직 요청이 없습니다.</p>'}</section><section class="surface"><div class="section-head"><h2>모의 주문 기록</h2><button id="reload-history" class="secondary">새로고침</button></div>${history.map(r=>{const link=transactionLink(r.audit_report);return `<div class="receipt-entry"><button class="receipt-row" data-receipt="${e(r.id)}"><span><strong>${e(r.data.quote.name)}</strong><small>${e(date(r.created_at))}</small></span><span>${money(r.data.quote.total,r.data.quote.currency)} ${badge(name(r.audit_state??'PENDING'))}</span><span aria-hidden="true">↗</span></button>${link?`<a class="secondary explorer-link" href="${e(link)}" target="_blank" rel="noopener noreferrer" aria-label="${e(r.data.quote.name)} 감사 거래를 Sepolia Etherscan에서 확인">Etherscan에서 확인 ${icon('next',18)}</a>`:''}</div>`;}).join('')||'<p>아직 주문 기록이 없습니다.</p>'}${receipt?`<div class="subsection"><h3>${e(receipt.quote.name)} ${badge('모의 주문','amber')}</h3><dl class="facts">${row('합계',money(receipt.quote.total,receipt.quote.currency))}${row('정책','v'+e(receipt.policyVersion))}${row('감사 상태',e(name(audit?.state??'PENDING')))}</dl><p>실제 주문·청구·배송이 없는 모의 영수증입니다.</p>${detailLink?`<p class="hash">트랜잭션 ${e(audit.report.txHash)}</p><a class="secondary explorer-link" href="${e(detailLink)}" target="_blank" rel="noopener noreferrer">Etherscan에서 확인 ${icon('next',18)}</a>`:'<p class="warning-text">확인된 온체인 기록이 아직 없습니다.</p>'}</div>`:''}</section>`;}
function activityPanel(){return `<details open><summary>AI 작업 요약${agentWorking?' · 진행 중':''}</summary><ul>${activitySteps(run,agentWorking).map(step=>`<li>${e(step)}</li>`).join('')}</ul></details>`;}
async function resumeAgent(){
 const runId=run.id;agentWorking=true;let polling=false,finished=false;
 const draw=()=>{const target=document.getElementById('agent-activity');if(target)target.innerHTML=activityPanel();};draw();
 const timer=setInterval(async()=>{if(polling||document.hidden)return;polling=true;try{const latest=await api('/agent/runs/'+runId);if(!finished&&run?.id===runId){run=latest;draw();}}catch{}finally{polling=false;}},4000);
 try{await api('/agent/runs/'+runId+'/resume','POST',{});}finally{finished=true;clearInterval(timer);agentWorking=false;draw();}
 await refresh();
}
function settingsPage(){return `<section class="surface"><div class="section-head"><h2>블록체인 트랜잭션</h2><button id="refresh-audits" class="secondary">새로고침</button></div><dl class="facts">${row('네트워크','Sepolia · 11155111')}${row('감사 연결',health?.configured?.audit?'연결 준비됨':'연결 미준비')}${row('주문 방식','모의 주문')}${row('가스 지불',health?.gasMode==='RELAYED'?'서비스 대납':health?.gasMode==='PERSONAL'?'개인 지갑':'미연결')}</dl><p class="muted">구매 승인 후 생성된 실제 감사 트랜잭션을 확인합니다. 실제 상품 결제는 발생하지 않습니다.</p>${connected?`<section class="wallet-card"><h3>내 Sepolia 지갑</h3>${wallet?.address?`<p class="hash">${e(wallet.address)}</p><p>${health?.gasMode==='RELAYED'?'감사 가스는 서비스가 대납합니다.':wallet.funded?'테스트 ETH 확인됨':'테스트 ETH 확인 대기 · 전송은 차단됨'}</p>`:`<p>개인 지갑이 없습니다.</p><button id="create-wallet" class="secondary"${dis(wallet?.state==='REQUESTED')}>${wallet?.state==='REQUESTED'?'발급 대기':'지갑 만들기'}</button>`}</section>`:''}${!health?.configured?.audit?'<p class="warning-text">'+e(explain('AUDIT_NOT_READY'))+'</p>':''}${!connected?'<a class="primary" href="/login" data-auth-route="/login">로그인</a>':audits.length?audits.map(a=>{const r=a.report,link=transactionLink(r);return `<article class="audit-record"><div class="section-head"><h3>${e(a.name||'모의 주문')}</h3>${badge(name(a.state))}</div><small>${e(date(a.created_at))}</small>${link?`<dl class="facts">${row('블록',e(r.blockNumber??'확인 필요'))}${row('실행 결과',r.receiptStatus===1?'성공':r.receiptStatus===0?'실패':'미확인')}${row('검증',r.verification==='verified'?'검증됨':'미확인')}${row('최종 확정',r.finality==='finalized'?'확정됨':'미확정')}</dl><p class="hash">${e(r.txHash)}</p><a class="secondary explorer-link" href="${e(link)}" target="_blank" rel="noopener noreferrer">Sepolia에서 확인 ${icon('next',18)}</a>`:'<p>확인된 트랜잭션 해시가 없습니다.</p>'}</article>`;}).join(''):'<div class="empty compact"><p>아직 트랜잭션 기록이 없습니다.</p></div>'}</section>`;}
function navigateAuth(path:string){if(path==='/'){if(edit){notice=explain('POLICY_BUSY');isError=true;render();return;}page='purchase';}window.history.pushState(null,'',path);notice='';isError=false;render();window.scrollTo(0,0);const title=app.querySelector('h1');if(title){title.tabIndex=-1;title.focus();}}
function render(){
 const view=!connected&&['/login','/signup'].includes(location.pathname)?location.pathname:page;
 if(renderedView&&renderedView!==view)queueMicrotask(()=>{const title=app.querySelector('h1');if(title){title.tabIndex=-1;title.focus();}});
 renderedView=view;
 document.title=view==='/login'?'로그인 · 구매':view==='/signup'?'회원가입 · 구매':view==='policy'?'정책 · 구매':view==='history'?'주문 기록 · 구매':view==='settings'?'설정 · 구매':'구매';
 mountAppControls();
 if(['/login','/signup'].includes(location.pathname)&&!connected){app.innerHTML=authPage(location.pathname==='/signup',notice,isError);bind();return;}
 if(connected&&['/login','/signup'].includes(location.pathname))window.history.replaceState(null,'','/');
 app.innerHTML=`<div class="app-shell"><aside class="sidebar"><a class="app-brand" href="/" data-auth-route="/">${icon('bag',25)}<span>구매</span></a><nav aria-label="주 메뉴">${[['purchase','구매'],['policy','정책'],['history','기록'],['settings','설정']].map(([id,t])=>`<button data-page="${id}" class="nav-item ${page===id?'active':''}" aria-current="${page===id?'page':'false'}"${dis(id==='policy'&&policy?.busy)}>${icon(id==='purchase'?'home':id==='policy'?'policy':id==='settings'?'settings':'history',23)}<span>${t}</span></button>`).join('')}</nav><p class="sidebar-note">실제 결제 없는<br>구매 시뮬레이션</p></aside><div class="workspace"><header class="topbar"><div class="page-heading"><h1>${page==='purchase'?'구매':page==='policy'?'정책':page==='settings'?'설정':'주문 기록'}</h1><p class="page-context">실제 결제 없이 정책·요청·감사 기록을 확인합니다.</p></div><div class="top-actions">${badge('모의 주문','amber')}<button id="${connected?'disconnect':'connection-toggle'}" class="connection-button">${icon('user',18)}${connected?'로그아웃':'로그인'}</button></div></header>${notice?`<div role="${isError?'alert':'status'}" class="notification ${isError?'error':''}">${e(notice)}</div>`:''}

 ${connected&&scopes.length>1?`<div class="scope-bar"><label for="scope">정책</label><select id="scope"${dis(run?.active||edit)}>${scopes.map(s=>`<option value="${e(s.id)}"${s.id===scope?' selected':''}>${e(s.id)}</option>`).join('')}</select></div>`:''}
 <div class="help-row"><button id="tutorial-launch" class="tutorial-launch" type="button">처음이신가요?</button></div><main>${page==='purchase'&&!connected?guestHome():page==='purchase'?`${policy?`<section class="balance-card surface"><div><span class="overline">모의 잔고</span><strong class="balance-amount">${money(policy.balance?.balance)}</strong></div><span class="icon-tile blue">${icon('wallet',28)}</span><dl><div><dt>예약 중</dt><dd>${money(policy.balance?.reserved)}</dd></div><div><dt>거래 한도</dt><dd>${money(policy.policy.maxPerTransaction)}</dd></div></dl></section>`:''}<div class="content-grid"><div>${run?.active?'':policy?requestForm():`<section class="surface"><h2>구매 정책이 없습니다</h2><button id="go-policy" class="primary">정책 추가하기</button></section>`}${runPanel()}</div><aside class="policy-rail surface ${policyExpanded?'expanded':''}"><button id="policy-expand" class="policy-expand" aria-expanded="${policyExpanded}">정책 · 읽기 전용 <span>${policyExpanded?'−':'+'}</span></button><div class="policy-content">${policySummary()}</div></aside></div>`:page==='policy'?policyPage():page==='settings'?settingsPage():historyPage()}</main></div></div>`;bind();}
function on(id:string,fn:()=>Promise<void>){document.getElementById(id)?.addEventListener('click',()=>void action(fn));}
function form(id:string,fn:()=>Promise<void>){document.getElementById(id)?.addEventListener('submit',ev=>{ev.preventDefault();void action(fn);});}
function canonical(v:any):string{return Array.isArray(v)?'['+v.map(canonical).join(',')+']':v&&typeof v==='object'?'{'+Object.keys(v).sort().map(k=>JSON.stringify(k)+':'+canonical(v[k])).join(',')+'}':JSON.stringify(v);}
async function answer(payload:any){await api('/agent/runs/'+run.id+'/events','POST',{eventId:crypto.randomUUID(),expectedVersion:run.version,type:'ANSWER',payload});await refresh();}
function bind(){
 on('refresh-audits',async()=>{health=await api(connected?'/audit/status':'/health');audits=connected?await api('/audits'):[];wallet=connected?await api('/wallet'):null;});on('create-wallet',async()=>{await api('/wallet','POST',{});wallet=await api('/wallet');});
 on('show-settings',async()=>{page='settings';health=await api('/audit/status');audits=await api('/audits');wallet=await api('/wallet');});
 document.querySelectorAll<HTMLInputElement>('input[data-amount]').forEach(input=>{const hint=document.createElement('small');hint.className='amount-hint';hint.id=input.id+'-hint';const label=input.parentElement?.querySelector('span');if(label){label.id=input.id+'-label';input.setAttribute('aria-labelledby',label.id);}input.setAttribute('aria-describedby',hint.id);input.after(hint);const control=input.id.startsWith('setup-')?'setup-currency':input.id.startsWith('policy-')?'policy-currency':null;const show=()=>{const currency=(control?value(control):'')||policy?.policy.currency||'KRW';const digits=new Intl.NumberFormat('en',{style:'currency',currency}).resolvedOptions().maximumFractionDigits??0;hint.textContent=/^[0-9]{1,15}$/.test(input.value)?money(input.value,currency,digits):'';};input.addEventListener('input',show);if(control)document.getElementById(control)?.addEventListener('change',show);show();});
 document.getElementById('tutorial-launch')?.addEventListener('click',startTutorial);
 document.getElementById('policy-expand')?.addEventListener('click',ev=>{policyExpanded=!policyExpanded;const button=ev.currentTarget as HTMLButtonElement;button.setAttribute('aria-expanded',String(policyExpanded));button.querySelector('span')!.textContent=policyExpanded?'−':'+';button.closest('.policy-rail')?.classList.toggle('expanded',policyExpanded);});
 on('connection-toggle',async()=>{navigateAuth('/login');});
 document.querySelectorAll<HTMLAnchorElement>('[data-auth-route]').forEach(a=>a.addEventListener('click',ev=>{ev.preventDefault();navigateAuth(a.dataset.authRoute!);}));
 form('signup-form',async()=>{
  if(!authClient||!signupEnabled)throw Error('SIGNUP_UNAVAILABLE');
  const email=await accountEmail(value('email')),password=value('password');if(password!==value('password-confirm'))throw Error('PASSWORD_MISMATCH');
  const {data,error}=await authClient.auth.signUp({email,password});if(error)throw Error('SIGNUP_FAILED');if(!data.session){notice='즉시 가입 설정이 적용되지 않았습니다. 관리자에게 문의하세요.';isError=true;return;}await loadAccount();notice='가입되었습니다.';
 });
 form('connect-form',async()=>{
  if(authClient){const {error}=await authClient.auth.signInWithPassword({email:await accountEmail(value('email')),password:value('password')});if(error)throw Error('LOGIN_FAILED');}
  else token=value('token');
  await loadAccount();
 });
 form('setup-form',async()=>{
  if(!check('setup-consent'))throw Error('PURCHASE_APPROVAL_REQUIRED');
  const currency='KRW',list=(id:string)=>value(id).split(',').map(s=>s.trim()).filter(Boolean),budget=value('setup-budget');
  const draft={currency,minorDigits:0,maxBudget:budget,maxPerTransaction:value('setup-transaction')||budget,minimumRemaining:value('setup-remaining')||'0',validUntil:value('setup-until')?new Date(value('setup-until')).toISOString():new Date(Date.now()+365*86400000).toISOString(),allowedMerchants:list('setup-allow'),blockedMerchants:list('setup-block'),blockedBrands:list('setup-brands'),minimumReviewScore:value('setup-review')?Number(value('setup-review')):null,preferLowerPrice:true,preferHigherReviewScore:false};
  const hash=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(canonical(draft)));
  await api('/setup','POST',{policy:draft,balance:value('setup-balance')||budget,approvedDigest:Array.from(new Uint8Array(hash),x=>x.toString(16).padStart(2,'0')).join('')});await loadAccount();showSetup=false;notice='정책을 저장했습니다.';
 });
 on('disconnect',async()=>{if(authClient)await authClient.auth.signOut();token='';audits=[];wallet=null;connected=false;run=null;policy=null;scopes=[];recent=[];history=[];edit=null;receipt=null;audit=null;selected='';});
 document.querySelectorAll<HTMLButtonElement>('[data-page]').forEach(b=>b.addEventListener('click',()=>void action(async()=>{if(edit&&b.dataset.page!==page)throw Error('POLICY_BUSY');page=b.dataset.page!;window.scrollTo(0,0);if(page==='history'&&connected)history=await api('/receipts');if(page==='settings'){health=await api(connected?'/audit/status':'/health');audits=connected?await api('/audits'):[];wallet=connected?await api('/wallet'):null;}if(connected)await refresh();})));
 document.getElementById('scope')?.addEventListener('change',()=>void action(async()=>{scope=value('scope');run=null;await refresh();}));
 form('request-form',async()=>{if(!connected)throw Error('UNAUTHORIZED');const track=(document.querySelector('input[name="track"]:checked') as HTMLInputElement).value,input:any={query:value('query')},autoPurchase=check('auto-purchase');if(value('maxTotal'))input.maxTotal=value('maxTotal');if(value('quantity'))input.quantity=Number(value('quantity'));if(value('requiredName'))input.requiredName=value('requiredName');if(track==='HardInput'&&(!input.maxTotal||!input.quantity))throw Error('INVALID_INPUT');if(autoPurchase&&(track!=='HardInput'||!input.maxTotal||!input.quantity||!input.requiredName))throw Error('AUTO_PURCHASE_REQUIRES_FIXED_LIMITS');const r=await api('/agent/runs','POST',{scopeId:scope,track,input,autoPurchase});run={id:r.runId};await refresh();render();await resumeAgent();});
 on('resume',resumeAgent);on('go-policy',async()=>{page='policy';showSetup=true;});on('add-policy',async()=>{showSetup=true;});
 form('answer-form',async()=>{const p:any={query:value('answer-query')};if(value('answer-budget'))p.maxTotal=value('answer-budget');if(value('answer-quantity'))p.quantity=Number(value('answer-quantity'));if(value('answer-name'))p.requiredName=value('answer-name');await answer(p);await resumeAgent();});
 on('approve-constraints',async()=>{if(!check('constraints-check'))throw Error('CONSTRAINT_APPROVAL_REQUIRED');const ids=run.evaluations.filter((x:any)=>run.track==='Plan'?x.kind==='EXAMPLE':x.kind==='EVALUATION'&&x.result.allowed).slice(0,run.track==='Plan'?2:20).map((x:any)=>x.id);await api('/agent/runs/'+run.id+'/constraint-approvals','POST',{constraintVersion:run.constraint_version,policyDigest:run.policy_digest,trackEvidenceIds:ids});await refresh();await resumeAgent();});
 on('cancel',async()=>{await api('/agent/runs/'+run.id+'/events','POST',{eventId:crypto.randomUUID(),expectedVersion:run.version,type:'CANCEL',payload:{}});await refresh();});
 const it=run?.intents?.find((x:any)=>!['CANCELED','REJECTED'].includes(x.state));
 on('refresh-quote',async()=>{await api('/purchase-intents/'+it.id+'/refresh','POST',{});await refresh();});
 on('approve-purchase',async()=>{if(!check('final-check'))throw Error('PURCHASE_APPROVAL_REQUIRED');await api('/purchase-intents/'+it.id+'/approvals','POST',{quoteVersion:it.quote_version,expectedGeneration:it.generation,mode:'SIMULATION',requestKey:crypto.randomUUID()});await refresh();await resumeAgent();});
 for(const id of ['show-receipts','reload-history'])on(id,async()=>{page='history';history=await api('/receipts');if(receipt)audit=await api('/receipts/'+receipt.id+'/audit');});
 document.querySelectorAll<HTMLButtonElement>('[data-receipt]').forEach(b=>b.addEventListener('click',()=>void action(async()=>{receipt=await api('/receipts/'+b.dataset.receipt);audit=await api('/receipts/'+b.dataset.receipt+'/audit');})));
 document.querySelectorAll<HTMLButtonElement>('[data-run]').forEach(b=>b.addEventListener('click',()=>void action(async()=>{if(run?.active&&run.id!==b.dataset.run)throw Error('RUN_BUSY');run=await api('/agent/runs/'+b.dataset.run);scope=run.scope_id;page='purchase';await refresh();})));
 on('restore-edit',async()=>{edit={editId:policy.edit_id,baseVersion:policy.edit_base};});
 on('enter-edit',async()=>{edit=await api('/policy-edit-sessions','POST',{scopeId:scope});await refresh();});
 on('cancel-edit',async()=>{await api('/policy-edit-sessions/'+edit.editId,'DELETE',{scopeId:scope});edit=null;await refresh();});
 form('policy-form',async()=>{if(!check('policy-consent'))throw Error('INVALID_INPUT');const currency=value('policy-currency'),list=(id:string)=>value(id).split(',').map(s=>s.trim()).filter(Boolean),draft={...policy.policy,currency,minorDigits:new Intl.NumberFormat('en',{style:'currency',currency}).resolvedOptions().maximumFractionDigits,maxBudget:value('policy-budget'),maxPerTransaction:value('policy-transaction'),minimumRemaining:value('policy-remaining'),validUntil:new Date(value('policy-until')).toISOString(),allowedMerchants:list('policy-allow'),blockedMerchants:list('policy-block'),blockedBrands:list('policy-brands'),minimumReviewScore:value('policy-review')?Number(value('policy-review')):null,preferLowerPrice:check('policy-price'),preferHigherReviewScore:check('policy-rating')};const hash=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(canonical(draft)));await api('/policy-edit-sessions/'+edit.editId+'/publish','POST',{scopeId:scope,baseVersion:edit.baseVersion,draft,approvedDigest:Array.from(new Uint8Array(hash),x=>x.toString(16).padStart(2,'0')).join('')});edit=null;await refresh();notice='새 정책 버전을 발행했습니다.';});
}
window.addEventListener('popstate',()=>{notice='';isError=false;render();});
render();
if(authClient)void authClient.auth.getSession().then(({data})=>{if(data.session)void action(loadAccount);});
void api('/health').then(data=>{health=data;}).catch(err=>{notice=explain(err instanceof Error?err.message:'BACKEND_UNAVAILABLE');isError=true;render();});
setInterval(()=>{if(connected&&!busy&&!tutorialOpen()&&run?.active&&['PROCESSING','AUDIT_PENDING'].includes(run.state))void action(async()=>{if(run.state==='PROCESSING')await api('/agent/runs/'+run.id+'/process','POST',{}).catch(()=>{});else await api('/agent/runs/'+run.id+'/audit-process','POST',{}).catch(()=>{});await refresh();});},10000);
