import {cp,mkdir,readFile,writeFile} from 'node:fs/promises';
import {resolve,dirname} from 'node:path';
import {fileURLToPath} from 'node:url';
const root=resolve(dirname(fileURLToPath(import.meta.url)),'..');
const output=resolve(root,'.test-state/vercel-site');
await mkdir(output,{recursive:true});
for(const item of ['src','public','index.html','tsconfig.json','package.json'])await cp(resolve(root,'frontend',item),resolve(output,item),{recursive:true});
await cp(resolve(root,'api'),resolve(output,'api'),{recursive:true});
await cp(resolve(root,'backend/dist'),resolve(output,'backend/dist'),{recursive:true});
await cp(resolve(root,'python_worker/main.py'),resolve(output,'python_worker/main.py'));
await mkdir(resolve(output,'search_service'),{recursive:true});
await cp(resolve(root,'search_service/__init__.py'),resolve(output,'search_service/__init__.py'));
await cp(resolve(root,'search_service/providers.py'),resolve(output,'search_service/providers.py'));
await cp(resolve(root,'deploy/certs'),resolve(output,'deploy/certs'),{recursive:true});
await mkdir(resolve(output,'blockchain/scripts'),{recursive:true});
await cp(resolve(root,'blockchain/scripts/audit-safety.mjs'),resolve(output,'blockchain/scripts/audit-safety.mjs'));
await cp(resolve(root,'blockchain/scripts/audit-transaction.mjs'),resolve(output,'blockchain/scripts/audit-transaction.mjs'));
await mkdir(resolve(output,'blockchain/src'),{recursive:true});
await cp(resolve(root,'blockchain/src/runAudit.mjs'),resolve(output,'blockchain/src/runAudit.mjs'));
await mkdir(resolve(output,'blockchain/artifacts/contracts/AuditRecord.sol'),{recursive:true});
await cp(resolve(root,'blockchain/artifacts/contracts/AuditRecord.sol/AuditRecord.json'),resolve(output,'blockchain/artifacts/contracts/AuditRecord.sol/AuditRecord.json'));
const pkg=JSON.parse(await readFile(resolve(output,'package.json'),'utf8'));
const backend=JSON.parse(await readFile(resolve(root,'backend/package.json'),'utf8'));
pkg.dependencies={...pkg.dependencies,...backend.dependencies};
pkg.engines={node:'24.x'};
await writeFile(resolve(output,'package.json'),JSON.stringify(pkg,null,2)+'\n');
await writeFile(resolve(output,'requirements.txt'),'ddgs==9.16.0\npython-dotenv==1.2.3\n');
const config=JSON.parse(await readFile(resolve(root,'deploy/vercel.json'),'utf8'));
config.installCommand='npm install --ignore-scripts';
config.buildCommand='npm run build';
config.outputDirectory='dist';
await writeFile(resolve(output,'vercel.json'),JSON.stringify(config,null,2)+'\n');
await writeFile(resolve(output,'.vercelignore'),'.env*\nnode_modules\n/dist\n.git\n.agents\n');
console.log(output);
